name: Ruby code style

on: [pull_request]

env:
  PULL_REQUEST_NUMBER: ${{ github.event.number }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  code_style:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Ruby code style
      run: |
        gem install rubocop
        gem install octokit
        rubocop --format json | ruby .github/lib/rubocop-annotations.rb
